### ISSUE TITLE
Using fastai interpretation

### ISSUE THREAD

**Issue by hno2** [ohmeow/blurr#38] opened 2021-05-27 13:33 UTC
Hey there, 

first: Thanks for your awesome tool, that makes everything work so much smoother. 
I successfully trained a model and want to evaluate its performance.
I tried using `interp = Interpretation.from_learner(learn)`, but this fails with an error:

```
/usr/local/lib/python3.7/dist-packages/fastai/torch_core.py in nested_reorder(t, idxs)
    704     elif is_listy(t): return type(t)(nested_reorder(t_, idxs) for t_ in t)
    705     if t is None: return t
--> 706     raise TypeError(f"Expected tensor, tuple, list or L but got {type(t)}")
    707 
    708 # Cell

TypeError: Expected tensor, tuple, list or L but got <class 'dict'>
```
Am I missing something or is this an error on my side?
Thanks in Advance for your help.

**Comment by ohmeow** [comment] 2021-05-28 03:09
Good catch.

The problem is that in the transformers library, all the inputs and outputs are defined as dictionaries ... BUT all the fastai bit are designed to only work against tensors!  That's way I ended up writing my own replacement to `Learner.summary` for example.

Let me talk to the powers that be over at fastai and see if we can get dictionary support or else I'll have to write a blurr friendly version of this method.

Thanks for bringing this up :)

**Comment by hno2** [comment] 2021-06-04 08:13
Hey, can I bother you once more? 

How would you currently go about getting the top losses of a datset. 
`blurr_predict` cannot return the losses, right? And `with_loss=True` is (obviously?) not working as you described above.

**Comment by ohmeow** [comment] 2021-06-04 19:44
`probs, trgs, losses = learn.get_preds(with_loss=True)` should work just fine.  The problem is with the `with_input=True` argument; it can't handle returning dictionaries at the moment and is set to `True` when you run `Interpreation.from_learner`.

In terms of evaluation, I actually just use sci-kit learn by itself to build confusion matrices and view metrics like f-beta, accuracy, recall, and even roc-auc graphs/scores using the `probs` and `trgs` above.

**Comment by hno2** [comment] 2021-06-07 08:03
Thanks for your answer. That helps me get on the right track.
I tried exactly that (`probs, trgs, losses = learn.get_preds(dl=dls[1],with_loss=True)`), which works as intended for the test/validation dataset. But when I try to do the same on the train dataset (`dls[0]`), I get the following error

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-85-30c42a8e6b2e> in <module>()
----> 1 probs,trgt, losses = learn.get_preds(dl=dls[0], with_loss=True)

1 frames
/usr/local/lib/python3.7/dist-packages/fastai/learner.py in get_preds(self, ds_idx, dl, with_input, with_decoded, with_loss, act, inner, reorder, cbs, **kwargs)
    255                 res[pred_i] = act(res[pred_i])
    256                 if with_decoded: res.insert(pred_i+2, getattr(self.loss_func, 'decodes', noop)(res[pred_i]))
--> 257             if reorder and hasattr(dl, 'get_idxs'): res = nested_reorder(res, tensor(idxs).argsort())
    258             return tuple(res)
    259         self._end_cleanup()

/usr/local/lib/python3.7/dist-packages/fastai/torch_core.py in tensor(x, *rest, **kwargs)
    132            else _array2tensor(x) if isinstance(x, ndarray)
    133            else as_tensor(x.values, **kwargs) if isinstance(x, (pd.Series, pd.DataFrame))
--> 134            else as_tensor(x, **kwargs) if hasattr(x, '__array__') or is_iter(x)
    135            else _array2tensor(array(x), **kwargs))
    136     if res.dtype is torch.float64: return res.float()

RuntimeError: Could not infer dtype of iterator
```

Is that a problem with my dataset (although training works without issue)? Or am I doing something wrong here.

**Comment by ohmeow** [comment] 2021-06-07 19:23
The training DL is constructed a bit differently that the validation/test DL.

If you want to run the training DL though, you'll want to do this:
```
t_dl = learn.dls[0].new(shuffle=False, drop_last=False)
preds, targs, losses = learn.get_preds(dl=t_dl, with_loss=True)
```

**Comment by ohmeow** [comment] 2022-05-11 00:57
Closing this out as I think its resolved (if not, hit me/us up on the fastai discord)

**Closed by ohmeow** 2022-05-11 00:57 UTC
