### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by tyoc213** [ohmeow/blurr#26] opened 2021-01-25 06:42 UTC
Hi there, I'm having a side assert cuda device on `self.loss_grad.backward()`

https://gist.github.com/tyoc213/1527e3e26f0d037466077949becf0063

It seems that this type of errors are normally about a size mismatch between tensors? but couldn't pinpoint more than that on this issue.

**Comment by ohmeow** [comment] 2021-02-01 00:23
I looked at your code ... if this is a multi-label task, you need to change your loss function to `BCELogitsLoss`.

Also, you need to specify the number of labels in the HF config object (the default is 2) but it looks like you have a few more.  Maybe consult the multi-label example in the Examples folder and see if that helps.  Lmk.

**Comment by tyoc213** [comment] 2021-02-06 02:18
you are right, I think second time I cross with the error and forgot it

**Comment by ohmeow** [comment] 2021-02-09 17:07
Lmk if I can close this out.  I'm going to try and make some of this automated cuz its a common mistake I even make :)

**Comment by tyoc213** [comment] 2021-02-14 22:47
haha, sorry, have been trying to do some things and bad time manag skillz, if you haven't started automation I could give a shoot and hopefully report on the week or "pass the batton"

**Comment by tyoc213** [comment] 2021-02-21 02:01
Im having a weird error after try to install in colab (from source and from pip)


![image](https://user-images.githubusercontent.com/506234/108613296-1a743e80-73b6-11eb-8e50-657830111838.png)

**Comment by ohmeow** [comment] 2021-02-24 17:35
That looks really odd.

Have you tried doing this on colab?  Or maybe try creating a clean conda
environment and try that?  If pip is still broken lmk.

-wg

**Comment by ohmeow** [comment] 2021-03-13 01:13
I can't reproduce ... lmk if you are still having issues or else please close out the issue if you can :)

Thanks!

**Closed** 2021-04-03 20:31 UTC

**Comment by gamingflexer** [comment] 2022-04-08 16:16
`pip install ohmeow-blurr`

**Do this now packages are updated!!**
