### ISSUE TITLE
error of summarization issue while fine-tuning

### ISSUE THREAD

**Issue by Ghani-25** [ohmeow/blurr#29] opened 2021-02-26 16:52 UTC
Hello,

I have an error in this line.

learn.fit_one_cycle(1, lr_max=3e-5, cbs=fit_cbs)

the error i got is :

/usr/local/lib/python3.7/dist-packages/blurr/modeling/seq2seq/core.py in after_validate(self) 138 for score_key, score in res.items(): 139 if (f'{metric_name}{score_key}' not in self.custom_metric_vals): continue --> 140 self.custom_metric_vals[f'{metric_name}{score_key}'] = score.mean().item() 141 elif (is_listy(return_val)):

AttributeError: 'list' object has no attribute 'mean'.

Can you help me please?

**Comment by Ghani-25** [comment] 2021-03-01 10:06
@ohmeow can you please help me?

**Comment by ohmeow** [comment] 2021-03-01 17:24
I'm running the code today and will let ya know how it goes

**Comment by Ghani-25** [comment] 2021-03-01 17:38
@ohmeow thank you so much it’s been a week that i am stuck

**Comment by ohmeow** [comment] 2021-03-02 02:51
This is fixed in the 0.0.24 release.  Give it a go ... and if all is well,
please close out this issue.

The problem is a bit perplexing because I can only recreate it on colab
(all things being equal, it runs find on my local dl-rig).  Anyways, on
colab, the "bertscore" scores come back as a list (on my machine they come
back as a tensor) ... so I ended up just casting them to an np.array so
that it works in either case.

-wg

**Comment by Ghani-25** [comment] 2021-03-02 08:08
@ohmeow thank you

**Closed** 2021-03-02 08:08 UTC
